/**
 * Regenerate test/fixtures/replay-golden.json.
 *
 * Run this ONLY when a simulator change is intentional. The whole point of the
 * golden fixture is that an accidental change to the physics shows up as a
 * failing test rather than a silently different tower.
 *
 *   node tools/make-fixture.js
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { replay } from '../src/sim.js';

/** Round to 3dp, folding -0 onto 0 so the JSON round-trips identically. */
function r3(value) {
  const r = Math.round(value * 1000) / 1000;
  return Object.is(r, -0) ? 0 : r;
}

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'test', 'fixtures', 'replay-golden.json');

function actions(spec) {
  return spec.map(([issue, x], i) => ({
    issue,
    user: `player${(i % 3) + 1}`,
    x,
    at: new Date(Date.UTC(2026, 7, 12, 0, i * 11)).toISOString(),
  }));
}

const cases = [
  {
    name: 'a tidy stack that keeps standing',
    actions: actions([[101, 240], [102, 236], [103, 244], [104, 239], [105, 242]]),
  },
  {
    name: 'a drop off the left edge of the platform',
    actions: actions([[201, 240], [202, 140], [203, 240]]),
  },
  {
    name: 'a leaning stack that eventually goes over',
    actions: actions([[301, 200], [302, 214], [303, 228], [304, 242], [305, 256],
      [306, 270], [307, 284], [308, 298]]),
  },
];

const fixture = {
  note: 'Generated by tools/make-fixture.js. Regenerate only for intentional simulator changes.',
  cases: cases.map((c) => {
    const result = replay(c.actions);
    return {
      name: c.name,
      actions: c.actions,
      expected: {
        collapsed: result.collapsed,
        turnsPlayed: result.turns.length,
        // Rounded: the assertion is about the game outcome, not the last bit of
        // a double. Bit-exactness is covered separately in sim.test.js.
        height: r3(result.height),
        turns: result.turns.map((t) => ({
          issue: t.issue,
          height: r3(t.height),
          collapsed: t.collapsed,
          reason: t.reason,
        })),
        blocks: result.world.bodies.filter((b) => !b.static).map((b) => ({
          issue: b.issue,
          x: r3(b.x),
          y: r3(b.y),
          angle: r3(b.angle),
        })),
      },
    };
  }),
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${JSON.stringify(fixture, null, 2)}\n`);

process.stdout.write(`wrote ${OUT}\n`);
for (const c of fixture.cases) {
  process.stdout.write(`  ${c.name}: ${c.expected.turnsPlayed} turns, `
    + `height ${c.expected.height}, collapsed=${c.expected.collapsed}\n`);
}
